# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8s-zombie" do
  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "7692a7af7fd8fbf96d5a9fd5bb8b4d72d4359d213511e1eb215cb495afbf721c"
      url "https://github.com/4ugane/k8s-zombie/releases/download/v#{version}/k8s-zombie_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c743e9eafa8f44a678f8d4bdca6367ab2826555b5b891330c1046810e0a1f9b1"
      url "https://github.com/4ugane/k8s-zombie/releases/download/v#{version}/k8s-zombie_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "082087c1beaa1816f6139d91129d8331bff82b2092d3f90713f8d40c8fefe678"
      url "https://github.com/4ugane/k8s-zombie/releases/download/v#{version}/k8s-zombie_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a1cede671b1e8884e13d627315f8e84f4b7ea46c18cb1e0c3dd20be1b1600df5"
      url "https://github.com/4ugane/k8s-zombie/releases/download/v#{version}/k8s-zombie_#{version}_linux_amd64.tar.gz"
    end
  end

  name "k8s-zombie"
  desc "Scan Kubernetes clusters for orphaned resources burning budget, with AWS cost estimates"
  homepage "https://github.com/4ugane/k8s-zombie"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "k8s-zombie"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/k8s-zombie"]
    end
  end

  # No zap stanza required
end
