# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8s-zombie" do
  version "0.1.6"

  on_macos do
    on_arm do
      sha256 "847eab617d1d3c47e78b80498792df1964885b3e6d34d4e89c1ded34cdc86848"
      url "https://github.com/4ugane/k8s-zombie/releases/download/v#{version}/k8s-zombie_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "15cbbb47c475207b074fb2013af1727d2cd143e68ab35051c949ac7cac66592f"
      url "https://github.com/4ugane/k8s-zombie/releases/download/v#{version}/k8s-zombie_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a225b7f9b5469592c22f788281f91259d97d14c28635893a010d59d29a16a3d7"
      url "https://github.com/4ugane/k8s-zombie/releases/download/v#{version}/k8s-zombie_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e442e3d31399bdfe8d39b4225ca9874cbf9ed8abb5c0fd01c32b946e05ecf7dc"
      url "https://github.com/4ugane/k8s-zombie/releases/download/v#{version}/k8s-zombie_#{version}_linux_amd64.tar.gz"
    end
  end

  name "k8s-zombie"
  desc "Scan Kubernetes clusters for orphaned resources burning budget, with AWS cost estimates"
  homepage "https://github.com/4ugane/k8s-zombie"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "k8s-zombie"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/k8s-zombie"]
    end
  end

  # No zap stanza required
end
