# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8s-zombie" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "70fa892a7f26a82f4facae5484513a28d8c265c46dee2ff6b9377a389a33cf66"
      url "https://github.com/4ugane/k8s-zombie/releases/download/v#{version}/k8s-zombie_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8766f9e936059eec03b09379613a44e22168e68c3d286e51f6e99342544d83ff"
      url "https://github.com/4ugane/k8s-zombie/releases/download/v#{version}/k8s-zombie_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a9e0725588f73e11fa28d62191615b5b1681df642e53e5d58e4257f6ea75b696"
      url "https://github.com/4ugane/k8s-zombie/releases/download/v#{version}/k8s-zombie_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "03bb11008e5b583afad8d56503c5d58a26d08723d15712af4c19e375d0cd4b0b"
      url "https://github.com/4ugane/k8s-zombie/releases/download/v#{version}/k8s-zombie_#{version}_linux_amd64.tar.gz"
    end
  end

  name "k8s-zombie"
  desc "Scan Kubernetes clusters for orphaned resources burning budget, with AWS cost estimates"
  homepage "https://github.com/4ugane/k8s-zombie"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "k8s-zombie"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/k8s-zombie"]
    end
  end

  # No zap stanza required
end
